START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `admin`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `feedback`;
DROP TABLE IF EXISTS `locations`;
DROP TABLE IF EXISTS `pollution_levels`;
DROP TABLE IF EXISTS `activity_logs`;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;